"""Controlled enum values established by the accepted engineering baseline."""

from enum import StrEnum


class ConfigurationStatus(StrEnum):
    DEFECTIVE_TEST_INPUT = "DEFECTIVE_TEST_INPUT"
    CORRECTED_BASELINE = "CORRECTED_BASELINE"


class SourceAvailability(StrEnum):
    AVAILABLE = "AVAILABLE"
    UNAVAILABLE = "UNAVAILABLE"


class SwitchState(StrEnum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"


class SwitchingDeviceType(StrEnum):
    FEEDER_SOURCE_BREAKER = "FEEDER_SOURCE_BREAKER"
    SECTIONALISING_SWITCH = "SECTIONALISING_SWITCH"
    TIE_SWITCH = "TIE_SWITCH"


class EdgeSemantics(StrEnum):
    SWITCHABLE_DEVICE_CONNECTION = "SWITCHABLE_DEVICE_CONNECTION"


class TelemetryQuality(StrEnum):
    GOOD = "GOOD"
    UNCERTAIN = "UNCERTAIN"
    BAD = "BAD"


class FreshnessStatus(StrEnum):
    FRESH = "FRESH"
    STALE = "STALE"
    INVALID_TIMESTAMP = "INVALID_TIMESTAMP"


class BoundaryEvidenceCondition(StrEnum):
    TRUSTWORTHY_OPEN = "A_TRUSTWORTHY_OPEN"
    TRUSTWORTHY_CLOSED = "B_TRUSTWORTHY_CLOSED"
    UNTRUSTWORTHY_OR_ABSENT = "C_UNTRUSTWORTHY_OR_ABSENT"


class BoundaryProofStatus(StrEnum):
    PROVEN_OPEN = "PROVEN_OPEN"
    PROVEN_CLOSED = "PROVEN_CLOSED"
    UNPROVEN = "UNPROVEN"


class BoundaryOperationNeed(StrEnum):
    NONE_SATISFIED = "NONE_SATISFIED"
    OPEN_REQUIRED = "OPEN_REQUIRED"
    EVIDENCE_REQUIRED = "EVIDENCE_REQUIRED"


class RadialityStatus(StrEnum):
    RADIAL = "RADIAL"
    UNINTENDED_LOOP = "UNINTENDED_LOOP"


class ScenarioMode(StrEnum):
    FORMAL = "FORMAL"
    EXPLORATION = "EXPLORATION"


class EvidenceClass(StrEnum):
    FORMAL = "FORMAL"
    EXPLORATORY = "EXPLORATORY"


class ScenarioRunStatus(StrEnum):
    INITIALISED = "INITIALISED"
    ACTIVE = "ACTIVE"
    RUN_COMPLETE = "RUN_COMPLETE"
    CLOSED = "CLOSED"


class WorkflowStage(StrEnum):
    NORMAL = "NORMAL"
    POST_FAULT = "POST_FAULT"
    ISOLATING = "ISOLATING"
    FAULT_ISOLATED = "FAULT_ISOLATED"
    UPSTREAM_RESTORED = "UPSTREAM_RESTORED"
    RESTORATION_ASSESSED = "RESTORATION_ASSESSED"
    RESTORATION_EXECUTED = "RESTORATION_EXECUTED"


class NetworkStateLabel(StrEnum):
    N0 = "N0"
    N1 = "N1"
    N2 = "N2"
    N3 = "N3"
    N4 = "N4"
    N5 = "N5"


class FaultType(StrEnum):
    DISTRIBUTION_SECTION_FAULT = "DISTRIBUTION_SECTION_FAULT"


class AlarmType(StrEnum):
    FEEDER_TRIP = "FEEDER_TRIP"


class AlarmAcknowledgementState(StrEnum):
    UNACKNOWLEDGED = "UNACKNOWLEDGED"
    ACKNOWLEDGED = "ACKNOWLEDGED"


class ScenarioCommandType(StrEnum):
    INITIATE_FAULT = "INITIATE_FAULT"
    ACKNOWLEDGE_ALARM = "ACKNOWLEDGE_ALARM"
    OPERATE_ISOLATION_DEVICE = "OPERATE_ISOLATION_DEVICE"
    RESTORE_NORMAL_SOURCE = "RESTORE_NORMAL_SOURCE"
    ASSESS_RESTORATION = "ASSESS_RESTORATION"
    EXECUTE_RESTORATION = "EXECUTE_RESTORATION"
    RESET_RUN = "RESET_RUN"


class RestorationOutcome(StrEnum):
    NO_CANDIDATE = "NO_CANDIDATE"
    BLOCKED = "BLOCKED"
    REJECTED = "REJECTED"
    PERMITTED = "PERMITTED"


class PermissiveStatus(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    INSUFFICIENT = "INSUFFICIENT"


class RestorationCriterion(StrEnum):
    FAULT_ISOLATION = "FAULT_ISOLATION"
    ALTERNATE_SOURCE = "ALTERNATE_SOURCE"
    RADIAL_TOPOLOGY = "RADIAL_TOPOLOGY"
    TELEMETRY_VALIDITY = "TELEMETRY_VALIDITY"
    CAPACITY = "CAPACITY"


class OperationalEventType(StrEnum):
    SCENARIO_INITIALISED = "SCENARIO_INITIALISED"
    CONFIGURATION_SELECTED = "CONFIGURATION_SELECTED"
    FAULT_INITIATED = "FAULT_INITIATED"
    TELEMETRY_UPDATED = "TELEMETRY_UPDATED"
    DEVICE_STATE_CHANGE = "DEVICE_STATE_CHANGE"
    ALARM_GENERATED = "ALARM_GENERATED"
    ALARM_ACKNOWLEDGED = "ALARM_ACKNOWLEDGED"
    SWITCHING_ACTION = "SWITCHING_ACTION"
    TOPOLOGY_RECALCULATED = "TOPOLOGY_RECALCULATED"
    OUTAGE_UPDATED = "OUTAGE_UPDATED"
    RESTORATION_CANDIDATE_IDENTIFIED = "RESTORATION_CANDIDATE_IDENTIFIED"
    RESTORATION_NO_CANDIDATE = "RESTORATION_NO_CANDIDATE"
    RESTORATION_ASSESSED = "RESTORATION_ASSESSED"
    RESTORATION_ASSESSMENT_INVALIDATED = "RESTORATION_ASSESSMENT_INVALIDATED"
    SCENARIO_RESET = "SCENARIO_RESET"


class OperationalEventSource(StrEnum):
    SCENARIO_CONTROL = "SCENARIO_CONTROL"
    GIS = "GIS"
    SCADA = "SCADA"
    OPERATOR = "OPERATOR"
    ADMS_TOPOLOGY = "ADMS_TOPOLOGY"
    OMS = "OMS"
    ADMS_RESTORATION = "ADMS_RESTORATION"


class ValidationDefinitionStatus(StrEnum):
    ACCEPTED = "ACCEPTED"


class ValidationExecutionStatus(StrEnum):
    ACTIVE = "ACTIVE"
    FINALISED = "FINALISED"


class ValidationAttemptStatus(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    ACTIVE = "ACTIVE"
    INCOMPLETE = "INCOMPLETE"
    SUSPENDED = "SUSPENDED"
    EXECUTED = "EXECUTED"


class ValidationSuspensionCondition(StrEnum):
    VSC_001 = "VSC-001"
    VSC_002 = "VSC-002"
    VSC_003 = "VSC-003"
    VSC_004 = "VSC-004"
    VSC_005 = "VSC-005"


class SuspensionLifecyclePosition(StrEnum):
    PRE_EXECUTION_ENTRY = "PRE_EXECUTION_ENTRY"
    EXECUTION_IN_PROGRESS = "EXECUTION_IN_PROGRESS"
    EVIDENCE_FINALISATION = "EVIDENCE_FINALISATION"


class SuspensionRecordStatus(StrEnum):
    DRAFT = "DRAFT"
    FINALISED = "FINALISED"


class SuspensionAuthorityKind(StrEnum):
    ENGINEERING_REVIEW = "ENGINEERING_REVIEW"
    BACKEND_ASSURANCE = "BACKEND_ASSURANCE"


class CompositeConstituentSourceKind(StrEnum):
    EXECUTION_RESULT = "EXECUTION_RESULT"
    SUSPENSION_RESULT = "SUSPENSION_RESULT"


class CompositeCompletenessStatus(StrEnum):
    INCOMPLETE = "INCOMPLETE"
    COMPLETE = "COMPLETE"


class CompositeResultStatus(StrEnum):
    DRAFT = "DRAFT"
    FINALISED = "FINALISED"


class ValidationVerdict(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    NOT_RUN = "NOT_RUN"
    BLOCKED_TEST = "BLOCKED-TEST"


class RepeatRelationshipType(StrEnum):
    DIRECT_REPEAT = "DIRECT_REPEAT"
    REGRESSION = "REGRESSION"
