import { expect, test } from '@playwright/test'

test('stale telemetry visibly withholds unsafe isolation actions', async ({ page }) => {
  await page.goto('/demo')
  await page.getByRole('button', { name: 'Start stale-evidence walkthrough' }).click()

  await expect(page.getByTestId('formal-state')).toContainText('N0 · Normal network')
  await expect(page.getByTestId('affected-customers')).toHaveText('0')
  await expect(page.getByRole('button', { name: 'Start simulated fault at SEC-A2' })).toBeEnabled()
  await page.getByRole('button', { name: 'Start simulated fault at SEC-A2' }).click()
  await expect(page.getByTestId('formal-state')).toContainText('N1 · Fault active')
  await expect(page.getByTestId('affected-customers')).toHaveText('850')
  await expect(page.getByRole('button', { name: 'Open SW-A12 to isolate SEC-A2' })).toBeDisabled()
  await expect(page.getByText('Review alarm first')).toHaveCount(2)
  await page.getByRole('button', { name: 'Review and acknowledge the feeder-trip alarm' }).click()
  await page.getByRole('button', { name: 'Acknowledge this feeder-trip alarm' }).click()
  await page.getByRole('button', { name: 'Review the blocked isolation decision' }).click()
  await expect(page.getByTestId('affected-customers')).toHaveText('850')
  await expect(page.getByRole('heading', { name: 'Review why isolation authority was withheld' })).toBeVisible()
  await expect(page.getByText('Stale-telemetry safety case · 3 of 4')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Can the faulted section be safely separated from supply?' })).toBeVisible()
  await expect(page.getByText('ISOLATION NOT YET CONFIRMED')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Open SW-A12 to isolate SEC-A2' })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Open SW-A23 to isolate SEC-A2' })).toBeDisabled()
  await expect(page.getByText('Open position not confirmed')).toHaveCount(2)
  await expect(page.getByText(/too old or invalid for this decision/)).toHaveCount(2)
  await expect(page.getByText(/grey operation cards show what has been withheld/i)).toBeVisible()
  const safetyPanelBox = await page.locator('.action-panel').boundingBox()
  const safetyButtonBox = await page.getByRole('button', { name: 'Review stale telemetry evidence' }).boundingBox()
  expect(safetyPanelBox).not.toBeNull()
  expect(safetyButtonBox).not.toBeNull()
  expect(safetyButtonBox!.x).toBeGreaterThanOrEqual(safetyPanelBox!.x)
  expect(safetyButtonBox!.x + safetyButtonBox!.width).toBeLessThanOrEqual(safetyPanelBox!.x + safetyPanelBox!.width)
  await expect(page.getByRole('button', { name: 'Return to walkthrough selection' })).toBeVisible()

  const guidedNavigation = page.getByRole('navigation', { name: 'Workspace views' })
  await expect(guidedNavigation.getByRole('button')).toHaveCount(4)
  await expect(guidedNavigation.getByRole('button', { name: 'Alarm review' })).toBeVisible()
  await expect(guidedNavigation.getByRole('button', { name: 'Telemetry evidence' })).toHaveAttribute('aria-current', 'page')
  await expect(guidedNavigation.getByRole('button', { name: 'Restoration' })).toHaveCount(0)

  await page.getByRole('button', { name: 'Review stale telemetry evidence' }).click()
  await expect(page.locator('.telemetry-panel tbody tr')).toHaveCount(2)
  await expect(page.getByRole('row', { name: /SW-A12.*GOOD.*71\.000 s.*STALE.*INSUFFICIENT/i })).toBeVisible()
  await expect(page.getByRole('row', { name: /SW-A23.*GOOD.*71\.000 s.*STALE.*INSUFFICIENT/i })).toBeVisible()
  await expect(page.getByText(/A GOOD reading can therefore still be unusable when it is STALE/i)).toBeVisible()
  await page.getByRole('button', { name: 'Review safety result' }).click()
  await expect(page.getByRole('heading', { name: 'The application withheld unsafe switching authority' })).toBeVisible()
  await expect(page.getByText('WITHHELD', { exact: true })).toBeVisible()
  await expect(page.getByText('PASS', { exact: true })).toBeVisible()
  await expect(page.getByText(/Blocked.*operating outcome.*PASS.*validation verdict/i)).toBeVisible()
  await expect(page.getByText(/No defect investigation is required/i)).toBeVisible()
  await page.getByRole('button', { name: 'Return to walkthrough selection' }).click()
  await expect(page.getByRole('button', { name: 'Start trial' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Start stale-evidence walkthrough' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Start formal validation walkthrough' })).toHaveCount(0)
})
