import { expect, test, type Page } from '@playwright/test'

async function selectView(page: Page, name: string) {
  await page.getByRole('navigation', { name: 'Workspace views' }).getByRole('button', { name }).click()
}

async function executeConfirmed(page: Page, accessibleName: RegExp) {
  await page.getByRole('button', { name: accessibleName }).click()
}

test('SEC-B3 trial automatically preserves and exports separately classified evidence', async ({ page }) => {
  await page.goto('/demo')
  await page.getByRole('combobox', { name: 'Trial fault section' }).selectOption('SEC-B3')
  await page.getByRole('button', { name: 'Start trial' }).click()
  await expect(page.getByTestId('full-run-id')).toBeVisible()
  const ribbon = page.getByLabel('Persistent run context')
  await expect(ribbon.getByText('TRIAL', { exact: true })).toBeVisible()
  await expect(ribbon.getByText('TRIAL RECORD', { exact: true })).toBeVisible()
  await expect(ribbon.getByText('SEC-B3', { exact: true })).toBeVisible()
  const sourceRunId = await page.getByTestId('full-run-id').textContent()

  await selectView(page, 'Results & evidence')
  await expect(page.getByRole('heading', { name: 'Validation of the operating logic for this case', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'How the trial evidence is controlled and extended' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Multi-scenario validation campaigns' })).toBeVisible()
  await expect(page.getByText(/Catalogue\/reference view.*not a requirement for completing the current trial/i)).toBeVisible()
  await expect(page.getByText('Formal progress remains separate')).toHaveCount(0)
  await expect(page.getByRole('button', { name: /Start exploratory execution VT-EXP-ALL-001/ })).toHaveCount(0)
  await selectView(page, 'Operational')

  await page.getByRole('button', { name: 'Start simulated fault at SEC-B3' }).click()
  await expect(page.getByRole('button', { name: /^Open SW-B23 to isolate SEC-B3$/ })).toBeDisabled()
  await expect(page.getByText('Review alarm first')).toHaveCount(2)
  await page.getByRole('button', { name: 'Review and acknowledge the feeder-trip alarm' }).click()
  await page.getByRole('button', { name: 'Acknowledge this feeder-trip alarm' }).click()
  await page.getByRole('button', { name: 'Continue to fault isolation' }).click()
  const actionListBounds = await page.locator('.action-list').boundingBox()
  const nextActionBounds = await page.getByRole('button', { name: /^Open SW-B23 to isolate SEC-B3$/ }).boundingBox()
  expect(actionListBounds).not.toBeNull()
  expect(nextActionBounds).not.toBeNull()
  expect(nextActionBounds!.y).toBeGreaterThanOrEqual(actionListBounds!.y)
  expect(nextActionBounds!.y + nextActionBounds!.height).toBeLessThanOrEqual(actionListBounds!.y + actionListBounds!.height + 1)
  await executeConfirmed(page, /^Open SW-B23 to isolate SEC-B3$/)
  await executeConfirmed(page, /^Open SW-B34 to isolate SEC-B3$/)
  await executeConfirmed(page, /^Reclose BRK-B to restore the healthy upstream section$/)
  await page.getByRole('button', { name: 'Check alternate supply for healthy de-energised sections' }).click()
  await page.getByRole('button', { name: 'Run alternate-supply check' }).click()

  await selectView(page, 'Restoration')
  await expect(page.getByRole('heading', { name: 'PERMITTED', exact: true })).toBeVisible()
  await expect(page.getByText('FDR-B', { exact: true })).toBeVisible()
  await expect(page.getByText(/FDR-A \/ ZS-01/)).toBeVisible()
  await page.getByRole('button', { name: 'Apply alternate supply restoration' }).click()
  await expect(page.getByRole('heading', { name: 'Restoration completed' })).toBeVisible()

  await selectView(page, 'Results & evidence')
  await expect(page.getByRole('heading', { name: 'Results and saved evidence for this run' })).toBeVisible()
  const validationProcedure = page.getByRole('region', { name: 'How the trial evidence is controlled and extended' })
  await expect(validationProcedure.getByText('Immutable result saved')).toBeVisible()
  await expect(validationProcedure.getByText(/This run contributes the EXP-ALL-B3 constituent case/)).toBeVisible()
  const allSectionsCampaign = validationProcedure.getByRole('article', { name: 'Validation campaign: All represented fault locations' })
  await expect(allSectionsCampaign.getByText(/1 of \d+ cases preserved/)).toBeVisible()
  await expect(allSectionsCampaign.getByText('Current run saved')).toBeVisible()

  const sourceRecord = page.getByRole('article', { name: 'Saved evidence: VT-EXP-ALL-001' })
  await expect(sourceRecord.getByText('Trial', { exact: true })).toBeVisible()
  const explorationSummary = sourceRecord.getByLabel('Trial evidence summary')
  await expect(explorationSummary.locator('article')).toHaveCount(4)
  await expect(explorationSummary.getByText('960 customers affected')).toBeVisible()
  await expect(explorationSummary.getByText(/SW-B23 and SW-B34 proved the fault isolated/)).toBeVisible()
  await expect(explorationSummary.getByText('440 remained affected')).toBeVisible()
  await expect(explorationSummary.getByText(/520 customers were restored/)).toBeVisible()
  await expect(explorationSummary.getByText(/FDR-A carries 4\.100 MW, or 74\.5% of 5\.500 MW capacity/)).toBeVisible()
  await expect(explorationSummary.getByText('Final result')).toBeVisible()
  await expect(explorationSummary.getByText('230 customers remained affected')).toBeVisible()
  await expect(explorationSummary.getByText(/210 customers were restored from the alternate feeder/)).toBeVisible()
  const explorationSequence = sourceRecord.getByLabel('Trial operating sequence')
  await expect(explorationSequence.locator('article')).toHaveCount(6)
  await expect(explorationSequence.getByText('Normal network')).toBeVisible()
  await expect(explorationSequence.getByText('Fault and feeder trip')).toBeVisible()
  await expect(explorationSequence.getByText('Fault isolated')).toBeVisible()
  await expect(explorationSequence.getByText('Healthy upstream section restored')).toBeVisible()
  await expect(explorationSequence.getByText('Alternate supply checked')).toBeVisible()
  await expect(explorationSequence.getByText('Eligible healthy sections restored')).toBeVisible()
  await expect(sourceRecord.getByText('Ready to create')).toBeVisible()
  await sourceRecord.getByRole('button', { name: 'Create downloadable evidence package' }).click()
  await expect(page.getByTestId('full-run-id')).toHaveText(sourceRunId!)
  await expect(sourceRecord.getByText('Downloadable package recorded')).toBeVisible()
  await expect(explorationSummary.getByText('960 customers affected')).toBeVisible()
  await expect(explorationSummary.getByText('230 customers remained affected')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Latest-run evidence package' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Download evidence package (.zip)' })).toBeVisible()

  const resultsRestart = page.getByRole('region', { name: 'Clear the current workspace and try another fault section' })
  await expect(resultsRestart.getByRole('combobox', { name: 'Fault section for next trial' })).toHaveValue('SEC-B3')
  await resultsRestart.getByRole('button', { name: 'Reset and rerun SEC-B3' }).click()
  await expect(page.getByTestId('full-run-id')).not.toHaveText(sourceRunId!)
  await expect(ribbon.getByText('SEC-B3', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Start simulated fault at SEC-B3' })).toBeEnabled()

  const repeatedRunId = await page.getByTestId('full-run-id').textContent()
  const operationalSelector = page.locator('.summary-run-control')
  await operationalSelector.getByRole('combobox', { name: 'Fault section for next trial' }).selectOption('SEC-A2')
  await operationalSelector.getByRole('button', { name: 'Start clean trial at SEC-A2' }).click()
  await expect(page.getByTestId('full-run-id')).not.toHaveText(repeatedRunId!)
  await expect(ribbon.getByText('SEC-A2', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Start simulated fault at SEC-A2' })).toBeEnabled()
  await selectView(page, 'Results & evidence')
  await expect(page.getByRole('heading', { name: 'Earlier evidence packages' })).toBeVisible()
  await expect(page.locator('details.package-history')).toHaveCount(1)
})

test('a capacity-rejected trial continues directly to its valid saved result', async ({ page }) => {
  await page.goto('/demo')
  await page.getByRole('combobox', { name: 'Trial fault section' }).selectOption('SEC-A1')
  await page.getByRole('button', { name: 'Start trial' }).click()
  await page.getByRole('button', { name: 'Start simulated fault at SEC-A1' }).click()
  await page.getByRole('button', { name: 'Review and acknowledge the feeder-trip alarm' }).click()
  await page.getByRole('button', { name: 'Acknowledge this feeder-trip alarm' }).click()
  await page.getByRole('button', { name: 'Continue to fault isolation' }).click()
  await page.getByRole('button', { name: /^Open SW-A12 to isolate SEC-A1$/ }).click()
  await page.getByRole('button', { name: 'Check alternate supply for healthy de-energised sections' }).click()
  await page.getByRole('button', { name: 'Run alternate-supply check' }).click()
  await expect(page.getByRole('heading', { name: 'REJECTED', exact: true })).toBeVisible()
  await expect(page.getByText('RESULTING LOAD EXCEEDS CAPACITY')).toBeVisible()
  await expect(page.getByText('110.8%')).toBeVisible()
  await page.getByRole('button', { name: 'Review assurance and validation results' }).click()
  await expect(page.getByRole('heading', { name: 'Results and saved evidence for this run' })).toBeVisible()
  await expect(page.getByText('All defined checks passed')).toBeVisible()
  await expect(page.getByText('REJECTED', { exact: true }).first()).toBeVisible()
})
