import { expect, test, type Page } from '@playwright/test'

async function selectView(page: Page, name: string) {
  await page.getByRole('navigation', { name: 'Workspace views' }).getByRole('button', { name }).click()
}

async function executeConfirmed(page: Page, accessibleName: RegExp) {
  await page.getByRole('button', { name: accessibleName }).click()
}

test('SEC-B3 exploration automatically preserves and exports separately classified evidence', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('combobox', { name: 'Exploration fault section' }).selectOption('SEC-B3')
  await page.getByRole('button', { name: 'Start exploration' }).click()
  await expect(page.getByTestId('full-run-id')).toBeVisible()
  const ribbon = page.getByLabel('Persistent run context')
  await expect(ribbon.getByText('EXPLORATION', { exact: true })).toBeVisible()
  await expect(ribbon.getByText('EXPLORATORY', { exact: true })).toBeVisible()
  await expect(ribbon.getByText('SEC-B3', { exact: true })).toBeVisible()
  const sourceRunId = await page.getByTestId('full-run-id').textContent()

  await selectView(page, 'Results & evidence')
  await expect(page.getByRole('heading', { name: 'Validation of the operating logic for this case', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'How the exploration evidence is controlled and extended' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Multi-scenario validation campaigns' })).toBeVisible()
  await expect(page.getByText('Formal progress remains separate')).toHaveCount(0)
  await expect(page.getByRole('button', { name: /Start exploratory execution VT-EXP-ALL-001/ })).toHaveCount(0)
  await selectView(page, 'Operational')

  await page.getByRole('button', { name: 'Start simulated fault at SEC-B3' }).click()
  await page.getByRole('button', { name: 'Review and acknowledge the feeder-trip alarm' }).click()
  await page.getByRole('button', { name: 'Acknowledge this feeder-trip alarm' }).click()
  await page.getByRole('button', { name: 'Continue to fault isolation' }).click()
  await executeConfirmed(page, /^Open SW-B23 to isolate SEC-B3$/)
  await executeConfirmed(page, /^Open SW-B34 to isolate SEC-B3$/)
  await executeConfirmed(page, /^Reclose BRK-B to restore the healthy upstream section$/)
  await page.getByRole('button', { name: 'Check alternate supply for healthy de-energised sections' }).click()
  await page.getByRole('button', { name: 'Run alternate-supply check' }).click()

  await selectView(page, 'Restoration')
  await expect(page.getByRole('heading', { name: 'PERMITTED', exact: true })).toBeVisible()
  await expect(page.getByText('FDR-B', { exact: true })).toBeVisible()
  await expect(page.getByText(/FDR-A \/ ZS-01/)).toBeVisible()
  await page.getByRole('button', { name: 'Apply alternate supply restoration' }).click()
  await expect(page.getByRole('heading', { name: 'Restoration completed' })).toBeVisible()

  await selectView(page, 'Results & evidence')
  const validationProcedure = page.getByRole('region', { name: 'How the exploration evidence is controlled and extended' })
  await expect(validationProcedure.getByText('Immutable result saved')).toBeVisible()
  await expect(validationProcedure.getByText(/This run contributes the EXP-ALL-B3 constituent case/)).toBeVisible()
  const allSectionsCampaign = validationProcedure.getByRole('article', { name: 'Validation campaign: All represented fault locations' })
  await expect(allSectionsCampaign.getByText(/1 of \d+ cases preserved/)).toBeVisible()
  await expect(allSectionsCampaign.getByText('Current run saved')).toBeVisible()

  const sourceRecord = page.getByRole('article', { name: 'Saved evidence: VT-EXP-ALL-001' })
  await expect(sourceRecord.getByText('Exploration', { exact: true })).toBeVisible()
  const explorationSummary = sourceRecord.getByLabel('Exploration evidence summary')
  await expect(explorationSummary.locator('article')).toHaveCount(4)
  await expect(explorationSummary.getByText('960 customers affected')).toBeVisible()
  await expect(explorationSummary.getByText(/SW-B23 and SW-B34 proved the fault isolated/)).toBeVisible()
  await expect(explorationSummary.getByText('440 remained affected')).toBeVisible()
  await expect(explorationSummary.getByText(/520 customers were restored/)).toBeVisible()
  await expect(explorationSummary.getByText(/FDR-A carries 4\.100 MW, or 74\.5% of 5\.500 MW capacity/)).toBeVisible()
  await expect(explorationSummary.getByText('Final result')).toBeVisible()
  await expect(explorationSummary.getByText('230 customers remained affected')).toBeVisible()
  await expect(explorationSummary.getByText(/210 customers were restored from the alternate feeder/)).toBeVisible()
  const explorationSequence = sourceRecord.getByLabel('Exploration operating sequence')
  await expect(explorationSequence.locator('article')).toHaveCount(6)
  await expect(explorationSequence.getByText('Normal network')).toBeVisible()
  await expect(explorationSequence.getByText('Fault and feeder trip')).toBeVisible()
  await expect(explorationSequence.getByText('Fault isolated')).toBeVisible()
  await expect(explorationSequence.getByText('Healthy upstream section restored')).toBeVisible()
  await expect(explorationSequence.getByText('Alternate supply checked')).toBeVisible()
  await expect(explorationSequence.getByText('Eligible healthy sections restored')).toBeVisible()
  await expect(sourceRecord.getByText('Ready to create')).toBeVisible()
  await sourceRecord.getByRole('button', { name: 'Create downloadable evidence package' }).click()
  await expect(page.getByTestId('full-run-id')).toHaveText(sourceRunId!)
  await expect(sourceRecord.getByText('Downloadable package recorded')).toBeVisible()
  await expect(explorationSummary.getByText('960 customers affected')).toBeVisible()
  await expect(explorationSummary.getByText('230 customers remained affected')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Latest-run evidence package' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Download evidence package (.zip)' })).toBeVisible()
})
