import type { RestorationAssessment, WorkspaceProjection } from './api/contracts'

export const permittedAssessment: RestorationAssessment = {
  assessment_id: '10000000-0000-0000-0000-000000000001', assessment_sequence: 1,
  scenario_run_id: '20000000-0000-0000-0000-000000000001', configuration_id: 'network-configuration-v1.1', state_revision: 4,
  scenario_time: '2030-01-01T00:00:50.000Z', candidate: {
    candidate_id: '30000000-0000-0000-0000-000000000001', affected_feeder_id: 'FDR-A', alternate_feeder_id: 'FDR-B', alternate_source_id: 'ZS-01', alternate_source_breaker_id: 'BRK-B', tie_device_id: 'TS-01', requested_tie_state: 'CLOSED', proposed_section_ids: ['SEC-A3', 'SEC-A4'], proposed_path_edge_ids: ['EDGE-TS-01-2', 'EDGE-TS-01-1'], transferable_load_kw: 1500, proposed_restored_customer_count: 450,
  }, telemetry_snapshot_sha256: 'a'.repeat(64), source_availability_sha256: 'b'.repeat(64), telemetry_evidence: [{ point_id: 'PT-TS-01', entity_id: 'TS-01', value: 'OPEN', quality: 'GOOD', timestamp: '2030-01-01T00:00:00.000Z', revision: 4, age_ms: 50000, freshness: 'FRESH', overall_valid: true, reason_codes: [] }], source_availability: { 'ZS-01': 'AVAILABLE' }, permissives: [{ criterion: 'FAULT_ISOLATION', status: 'PASS', reason_codes: ['FAULT_ISOLATED'], evidence_point_ids: ['PT-SW-A23'] }, { criterion: 'CAPACITY', status: 'PASS', reason_codes: ['CAPACITY_SUFFICIENT'], evidence_point_ids: [] }], calculation: { alternate_feeder_id: 'FDR-B', existing_supplied_load_kw: 4200, transferable_load_kw: 1500, resulting_load_kw: 5700, feeder_capacity_kw: 6000, resulting_loading_percent: 95, capacity_pass: true }, outcome: 'PERMITTED', reason_codes: ['ALL_PERMISSIVES_PASS'],
}

export function makeProjection(overrides: Partial<WorkspaceProjection> = {}): WorkspaceProjection {
  const base: WorkspaceProjection = {
    application_build_id: '1'.repeat(64), configuration_status: 'CORRECTED_BASELINE',
    run: { scenario_run_id: '20000000-0000-0000-0000-000000000001', mode: 'FORMAL', configuration_id: 'network-configuration-v1.1', configuration_version: '1.1', fault_section_id: 'SEC-A2', fault_type: 'DISTRIBUTION_SECTION_FAULT', initial_scenario_time: '2030-01-01T00:00:00.000Z', scenario_time: '2030-01-01T00:00:50.000Z', state_revision: 4, workflow_stage: 'RESTORATION_ASSESSED', network_state_label: 'N4', evidence_class: 'FORMAL', application_build_id: '1'.repeat(64), status: 'ACTIVE', fault_active: true, source_availability: { 'ZS-01': 'AVAILABLE' } },
    summary: { de_energised_section_ids: ['SEC-A2', 'SEC-A3', 'SEC-A4'], affected_customer_count: 670, restored_customer_delta: 0, active_alarm_count: 1, unacknowledged_alarm_count: 0, current_assessment_status: 'PERMITTED', current_assessment_id: permittedAssessment.assessment_id, current_assessment_invalidated: false, radiality_status: 'RADIAL' },
    network_nodes: [{ entity_id: 'SEC-A2', position: { x: 640, y: 160 }, configured: { entity_id: 'SEC-A2', entity_type: 'SECTION', name: 'East Ridge Section 2', feeder_id: 'FDR-A', device_type: null, normal_state: null, normal_source_availability: null, configured_load_kw: 950, customer_zone_id: 'CZ-A2', customer_count: 220 }, observed: null, derived: { energised: false, source_feeder_ids: [], source_path_node_ids: [], current_source_availability: null }, fault_status: 'FAULTED' }, { entity_id: 'TS-01', position: { x: 1360, y: 330 }, configured: { entity_id: 'TS-01', entity_type: 'SWITCHING_DEVICE', name: 'Feeder Tie Switch', feeder_id: null, device_type: 'TIE_SWITCH', normal_state: 'OPEN', normal_source_availability: null, configured_load_kw: null, customer_zone_id: null, customer_count: null }, observed: { point_id: 'PT-TS-01', value: 'OPEN', quality: 'GOOD', timestamp: '2030-01-01T00:00:00.000Z', age_ms: 50000, freshness: 'FRESH', overall_valid: true, reason_codes: [] }, derived: { energised: null, source_feeder_ids: [], source_path_node_ids: [], current_source_availability: null }, fault_status: 'NOT_APPLICABLE' }],
    network_edges: [],
    feeders: [{ feeder_id: 'FDR-B', name: 'Riverbend Feeder', source_id: 'ZS-01', source_breaker_id: 'BRK-B', section_ids: ['SEC-B1', 'SEC-B2', 'SEC-B3', 'SEC-B4'], configured_capacity_kw: 6000, configured_normal_load_kw: 4200, derived_currently_supplied_load_kw: 5700, derived_load_attribution_complete: true, derived_supplied_section_ids: ['SEC-B1', 'SEC-B2', 'SEC-B3', 'SEC-B4', 'SEC-A3', 'SEC-A4'] }],
    telemetry: [{ point_id: 'PT-TS-01', entity_id: 'TS-01', value: 'OPEN', quality: 'GOOD', timestamp: '2030-01-01T00:00:00.000Z', age_ms: 50000, freshness: 'FRESH', quality_valid: true, timestamp_valid: true, overall_valid: true, reason_codes: [] }],
    alarms: [{ alarm_id: '40000000-0000-0000-0000-000000000001', scenario_run_id: '20000000-0000-0000-0000-000000000001', entity_id: 'BRK-A', alarm_type: 'FEEDER_TRIP', active: true, acknowledgement_state: 'ACKNOWLEDGED', generated_scenario_time: '2030-01-01T00:00:10.000Z', acknowledged_scenario_time: '2030-01-01T00:00:11.000Z', acknowledged_by: 'Graduate Engineer' }],
    events: [{ event_id: '50000000-0000-0000-0000-000000000001', scenario_run_id: '20000000-0000-0000-0000-000000000001', event_sequence: 1, scenario_time: '2030-01-01T00:00:00.000Z', state_revision: 0, source: 'SCENARIO_CONTROL', event_type: 'SCENARIO_INITIALISED', affected_entity_id: null, description: 'Controlled scenario initialised.', actor: 'Graduate Engineer', previous_value: null, new_value: null, command_id: null, alarm_id: null, assessment_id: null }],
    isolation_proof: null, restoration_assessments: [permittedAssessment], restoration_invalidations: [],
    allowed_actions: [{ action_id: 'EXECUTE_RESTORATION:assessment', command_type: 'EXECUTE_RESTORATION', target_entity_id: null, requested_state: null, alarm_id: null, assessment_id: permittedAssessment.assessment_id, available: true, reason_code: 'AVAILABLE', reason: 'Execution requires the current bound PERMITTED assessment.', expected_revision: 4, proposed_scenario_time: '2030-01-01T00:00:55.000Z', confirmation_required: true, confirmation_text: 'Simulated operation only — no real equipment control.' }, { action_id: 'RESTORE_NORMAL_SOURCE:BRK-A', command_type: 'RESTORE_NORMAL_SOURCE', target_entity_id: 'BRK-A', requested_state: 'CLOSED', alarm_id: null, assessment_id: null, available: false, reason_code: 'ISOLATION_NOT_PROVEN_AT_N2', reason: 'Requires current derived isolation proof at N2.', expected_revision: 4, proposed_scenario_time: '2030-01-01T00:00:40.000Z', confirmation_required: true, confirmation_text: 'Simulated operation only — no real equipment control.' }],
    validation: { definitions: [{ definition: { test_id: 'VT-FML-N0-N5-001', title: 'Complete formal SEC-A2 sequence', version: '1.0', status: 'ACCEPTED', evidence_class: 'FORMAL', requirement_ids: ['REQ-TOP-001'], source_references: ['Validation Plan §8'], objective: 'Complete formal SEC-A2 sequence', method: 'Controlled scenario', preconditions: ['Controlled N0'], controlled_inputs: ['Step 9 times'], procedure_steps: ['Execute N0 to N5'], checkpoint_obligations: ['N0', 'N1', 'N2', 'N3', 'N4', 'N5'].map((checkpoint_id) => ({ checkpoint_id, required_content: ['TOPOLOGY'] })), expected_result_statement: 'N1 850; N3 670; N4 PERMITTED; N5 220 affected.', comparison_expected_values: null, evidence_requirements: ['TOPOLOGY'], verdict_rule: 'Compare preserved evidence.', reset_repeat_rule: 'Preserve separate records.', constituent_cases: [] }, definition_sha256: '2'.repeat(64), catalogue_id: 'VALIDATION-CATALOGUE-V1.1', catalogue_version: '1.1', catalogue_sha256: '3'.repeat(64) }], run_executions: [], library_executions: [], composites: [], progress: { definition_count: 21, definitions_without_execution_count: 21, execution_count: 0, active_execution_count: 0, finalised_execution_count: 0, pass_count: 0, fail_count: 0, blocked_test_count: 0 }, actions: [{ action_type: 'START_EXECUTION', available: false, reason_code: 'REQUIRES_FORMAL_N0', reason: 'The controlled formal execution may start only against FORMAL N0.', test_id: 'VT-FML-N0-N5-001', case_id: null, validation_execution_id: null, checkpoint_id: null }] },
    conceptual_boundary_notice: 'Fictional local engineering demonstrator — no real equipment control.',
  }
  return { ...base, ...overrides }
}
